<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://at.fhv.ecss2016.restest/model" nsPrefix="restestModel">
  <eClassifiers xsi:type="ecore:EClass" name="Config">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verb" eType="#//HTTPVerb"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="#//ContentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestBody" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" eType="#//Response"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scenariosFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configResultPairs" upperBound="-1"
        eType="#//ConfigResultPair"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Response">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseContentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseBody" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpectedResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseContentType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseBody" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigResultPair">
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" eType="#//Config"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" eType="#//Response"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContentType">
    <eLiterals name="TEXT" literal=""/>
    <eLiterals name="TEXT_PLAIN" value="1"/>
    <eLiterals name="JSON" value="2"/>
    <eLiterals name="JAVASCRIPT" value="3"/>
    <eLiterals name="XML_TEXT" value="4"/>
    <eLiterals name="XML_APPLICATION" value="5"/>
    <eLiterals name="HTML" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HTTPVerb">
    <eLiterals name="GET"/>
    <eLiterals name="POST" value="1"/>
    <eLiterals name="PUT" value="2"/>
    <eLiterals name="DELETE" value="3"/>
  </eClassifiers>
</ecore:EPackage>
