<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://at.fhv.ecss2016.restest/model" nsPrefix="restestModel">
  <eClassifiers xsi:type="ecore:EClass" name="Config">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verb" eType="#//HttpVerb"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentType" eType="#//ContentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestBody" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" eType="#//Response"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scenariosFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configResultPairs" upperBound="-1"
        eType="#//ConfigResultPair"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Response">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseCode" eType="#//StatusCode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseContentType" eType="#//ContentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseBody" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpectedResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseCode" eType="#//StatusCode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseContentType" eType="#//ContentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseBody" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigResultPair">
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" eType="#//Config"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" eType="#//Response"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContentType">
    <eLiterals name="TEXT" literal="text"/>
    <eLiterals name="TEXT_PLAIN" value="1" literal="text/plain"/>
    <eLiterals name="JSON" value="2" literal="application/json"/>
    <eLiterals name="JAVASCRIPT" value="3" literal="application/javascript"/>
    <eLiterals name="XML_TEXT" value="4" literal="text/xml"/>
    <eLiterals name="XML_APPLICATION" value="5" literal="application/xml"/>
    <eLiterals name="HTML" value="6" literal="text/html"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HttpVerb">
    <eLiterals name="GET"/>
    <eLiterals name="POST" value="1"/>
    <eLiterals name="PUT" value="2"/>
    <eLiterals name="DELETE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StatusCode">
    <eLiterals name="CONTINUE" value="100"/>
    <eLiterals name="SWITCHING_PROTOCOLS" value="101"/>
    <eLiterals name="PROCESSING" value="102"/>
    <eLiterals name="OK" value="200"/>
    <eLiterals name="CREATED" value="201"/>
    <eLiterals name="ACCEPTED" value="202"/>
    <eLiterals name="NON_AUTHORITATIVE_INFORMATION" value="203"/>
    <eLiterals name="NO_CONTENT" value="204"/>
    <eLiterals name="RESET_CONTENT" value="205"/>
    <eLiterals name="PARTIAL_CONTENT" value="206"/>
    <eLiterals name="MULTI_STATUS" value="207"/>
    <eLiterals name="MULTIPLE_CHOICES" value="300"/>
    <eLiterals name="MOVED_PERMANENTLY" value="301"/>
    <eLiterals name="MOVED_TEMPORARILY" value="302"/>
    <eLiterals name="SEE_OTHER" value="303"/>
    <eLiterals name="NOT_MODIFIED" value="304"/>
    <eLiterals name="USE_PROXY" value="305"/>
    <eLiterals name="TEMPORARY_REDIRECT" value="307"/>
    <eLiterals name="BAD_REQUEST" value="400"/>
    <eLiterals name="UNAUTHORIZED" value="401"/>
    <eLiterals name="PAYMENT_REQUIRED" value="402"/>
    <eLiterals name="FORBIDDEN" value="403"/>
    <eLiterals name="NOT_FOUND" value="404"/>
    <eLiterals name="METHOD_NOT_ALLOWED" value="405"/>
    <eLiterals name="NOT_ACCEPTABLE" value="406"/>
    <eLiterals name="PROXY_AUTHENTICATION_REQUIRED" value="407"/>
    <eLiterals name="REQUEST_TIMEOUT" value="408"/>
    <eLiterals name="CONFLICT" value="409"/>
    <eLiterals name="GONE" value="410"/>
    <eLiterals name="LENGTH_REQUIRED" value="411"/>
    <eLiterals name="PRECONDITION_FAILED" value="412"/>
    <eLiterals name="REQUEST_TOO_LONG" value="413"/>
    <eLiterals name="REQUEST_URI_TOO_LONG" value="414"/>
    <eLiterals name="UNSUPPORTED_MEDIA_TYPE" value="415"/>
    <eLiterals name="REQUESTED_RANGE_NOT_SATISFIABLE" value="416"/>
    <eLiterals name="EXPECTATION_FAILED" value="417"/>
    <eLiterals name="INSUFFICIENT_SPACE_ON_RESOURCE" value="419"/>
    <eLiterals name="METHOD_FAILURE" value="420"/>
    <eLiterals name="UNPROCESSABLE_ENTITY" value="422"/>
    <eLiterals name="LOCKED" value="423"/>
    <eLiterals name="FAILED_DEPENDENCY" value="424"/>
    <eLiterals name="INTERNAL_SERVER_ERROR" value="500"/>
    <eLiterals name="NOT_IMPLEMENTED" value="501"/>
    <eLiterals name="BAD_GATEWAY" value="502"/>
    <eLiterals name="SERVICE_UNAVAILABLE" value="503"/>
    <eLiterals name="GATEWAY_TIMEOUT" value="504"/>
    <eLiterals name="HTTP_VERSION_NOT_SUPPORTED" value="505"/>
    <eLiterals name="INSUFFICIENT_STORAGE" value="507"/>
  </eClassifiers>
</ecore:EPackage>
